<?php declare(strict_types=1); require_once __DIR__.'/../src/auth/session.php';require_once __DIR__.'/../config/app.php';require_once __DIR__.'/../src/actions/task_queries.php';require_once __DIR__.'/../src/actions/task_state_machine.php';require_once __DIR__.'/../src/finance/payouts.php'; requireAuth(); $u=$_SESSION['user'];$r=$u['role'];
if($_SERVER['REQUEST_METHOD']==='POST'){ $a=$_POST['action']??''; if($r===ROLE_ADMIN&&$a==='create_task'){createTask(trim($_POST['title']),trim($_POST['description']), (int)$_POST['assignee_id'],(float)$_POST['task_value']);}
if(($r===ROLE_EMPLOYEE||$r===ROLE_CORE_EMPLOYEE)&&$a==='start_task'){setTaskInProgress((int)$_POST['task_id'],(int)$u['id']);}
if(($r===ROLE_EMPLOYEE||$r===ROLE_CORE_EMPLOYEE)&&$a==='submit_task'){submitTaskForQa((int)$_POST['task_id'],(int)$u['id'],trim($_POST['delivery_path']));}
if($r===ROLE_QA&&$a==='qa_decision'){qaDecision((int)$_POST['task_id'],($_POST['approved']??'')==='1',trim($_POST['qa_notes']??''));}
if($r===ROLE_ACCOUNTS&&$a==='mark_paid'){markCommissionPaid((int)$_POST['task_id'],(int)$u['id']);}
header('Location: /dashboard.php'); exit; }
?><!doctype html><html><body><h1><?=htmlspecialchars($r)?> Dashboard</h1><a href='/logout.php'>Logout</a>
<?php if($r===ROLE_ADMIN): $employees=allEmployees(); ?><h2>Create Task</h2><form method='post'><input type='hidden' name='action' value='create_task'><input name='title' required><input name='description'><input name='task_value' type='number' step='0.01' required><select name='assignee_id'><?php foreach($employees as $e):?><option value='<?=$e['id']?>'><?=htmlspecialchars($e['name'].' '.$e['role'])?></option><?php endforeach;?></select><button>Create</button></form><?php endif;?>
<?php if($r===ROLE_EMPLOYEE||$r===ROLE_CORE_EMPLOYEE): $tasks=tasksForEmployee((int)$u['id']);?><h2>My Tasks</h2><?php foreach($tasks as $t):?> <div>#<?=$t['id']?> <?=htmlspecialchars($t['title'])?> [<?=htmlspecialchars($t['status'])?>]
<?php if($t['status']==='Pending'||$t['status']==='Needs Revision'):?><form method='post'><input type='hidden' name='action' value='start_task'><input type='hidden' name='task_id' value='<?=$t['id']?>'><button>Start</button></form><?php endif;?>
<?php if($t['status']==='In Progress'):?><form method='post'><input type='hidden' name='action' value='submit_task'><input type='hidden' name='task_id' value='<?=$t['id']?>'><input name='delivery_path' required><button>Submit QA</button></form><?php endif;?></div><?php endforeach; endif;?>
<?php if($r===ROLE_QA): $q=tasksByStatus('QA Review');?><h2>QA Queue</h2><?php foreach($q as $t):?><div>#<?=$t['id']?> <?=htmlspecialchars($t['title'])?><form method='post'><input type='hidden' name='action' value='qa_decision'><input type='hidden' name='task_id' value='<?=$t['id']?>'><input name='qa_notes'><button name='approved' value='1'>Approve</button><button name='approved' value='0'>Reject</button></form></div><?php endforeach; endif;?>
<?php if($r===ROLE_ACCOUNTS): $d=tasksByStatus('Delivered');?><h2>Delivered</h2><?php foreach($d as $t):?><div>#<?=$t['id']?> <?=htmlspecialchars($t['title'])?> payout <?=number_format(calculateCommissionAmount($t),2)?> [<?=$t['payout_status']?>] <?php if($t['payout_status']==='Pending'):?><form method='post'><input type='hidden' name='action' value='mark_paid'><input type='hidden' name='task_id' value='<?=$t['id']?>'><button>Mark Paid</button></form><?php endif;?></div><?php endforeach; endif;?></body></html>
